### ISSUE TITLE
Not working if url contains default.aspx

### ISSUE THREAD

**Issue by sankarkumar23** [SPFxAppDev/sp-quicklinks-browser-extension#1]
Due to migration, I have a default.aspx page as a home page for SPO sites

**Comment by SPFxAppDev** [comment]
Hello and thank you for your report. Can you tell me what version you are using? The latest one? v0.0.5?

**Comment by sankarkumar23** [comment]
> Hello and thank you for your report. Can you tell me what version you are using? The latest one? v0.0.5?

Latest only.. downloaded it yesterday.

**Comment by SPFxAppDev** [comment]
Could you send me the URL please? Then I can have a look at it. I don't need the full URL, just what's after the site url.

**Comment by sankarkumar23** [comment]
https://xxx.sharepoint.com/sites/somesite/default.aspx
ended up like this.. appears this scenario was not handled in the code.
https://xxx.sharepoint.com/sites/somesite/default.aspx/_layouts/15/viewlsts.aspx

**Comment by SPFxAppDev** [comment]
Okay, thanks. I'll look into that and fix it. I will let you know when it is done

**Comment by SPFxAppDev** [comment]
Hi @sankarkumar23,

I have published a new version (0.0.6). It should work now and the problem should be fixed. Please let me know if not.  If I don't get any feedback in a few days, then I will assume it is fixed and close the bug

Regards

Seryoga

**Comment by sankarkumar23** [comment]
It's working fine now. Thanks!
